### ISSUE TITLE
Things to do on main page

### ISSUE THREAD

**Issue by ktm07** [jjm7HWU/Web-Development-MMO#22]
Guys, we have to figure out what things should be on the main page like login, username and score etc.

**Comment by jcc8HW** [comment]
Yes, you are right! That's very important.
we will work on the back end, once we sorted out that we can do that.

**Comment by jcc8HW** [comment]
you can create a simple form for the email and user name

**Comment by ktm07** [comment]
sure jose

**Comment by jjm7HWU** [comment]
I think you guys have done this now. Good job.
