### ISSUE TITLE
Restart option

### ISSUE THREAD

**Issue by jcc8HW** [jjm7HWU/Web-Development-MMO#62]
Player can restart after losing

**Comment by jjm7HWU** [comment]
In popular io games there seems to be a convention of having the home page and the restart page as the same page. Do you think that this would be a good idea when we revamp the home page? It will make just a single entry point.

**Comment by jcc8HW** [comment]
Yeah that is a vey good idea, I think we should try that and test it

**Comment by jjm7HWU** [comment]
Seems to work nicely now.
