### ISSUE TITLE
Add Tutorial pop up for game

### ISSUE THREAD

**Issue by jcc8HW** [jjm7HWU/Web-Development-MMO#64]
The users are a bit confused when they first play the game, because they dont k ow the controls

**Comment by jjm7HWU** [comment]
Yeah this is something we should do. When we revamp the home page we can put it there if it would fit in well. Like this: http://splix.io/

Or as you suggested a pop up would be good. Would it be one that the user actively opens or is it whenever they visit the game?

**Comment by ktm07** [comment]
we can close this issue, Tutorial on the home screen is done
