### ISSUE TITLE
Restart game

### ISSUE THREAD

**Issue by jcc8HW** [jjm7HWU/Web-Development-MMO#89]
When the player dies, he should be able to play again

**Comment by jjm7HWU** [comment]
Yeah I can get that done now. I was meant to have done that earlier than this. I am thinking of having the game continue to render the place the player died for a few seconds before redirecting them back to the home screen to play again. I'll implement and we can see what we think.

**Comment by jjm7HWU** [comment]
I have the player now redirected to homepage but only on localhost. We could have it redirect to the appropriate depending on if it is running locally or on heroku but in the final deployment we will only need one so I am not sure whether it is worthwhile having such an implementation. It looks great though. And now there is also no error when the player dies.

**Comment by jcc8HW** [comment]
I does not work on the server, I was being sent to my local host. I think the best strategy is to create a new socket io event, to restart the game. I can do that with Jack
